// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNHHOBYhC1ZYc1KDuQel24iCgk-5lsrCI',
    appId: '1:332419219143:web:f6b3f3bb5d9dda07cd48e2',
    messagingSenderId: '332419219143',
    projectId: 'chatapp-48416',
    authDomain: 'chatapp-48416.firebaseapp.com',
    storageBucket: 'chatapp-48416.firebasestorage.app',
    measurementId: 'G-9RJCC28HGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDfE4odPjtGssPD8D6AuItUw-_nURxavM',
    appId: '1:332419219143:android:0d98ba11402c065acd48e2',
    messagingSenderId: '332419219143',
    projectId: 'chatapp-48416',
    storageBucket: 'chatapp-48416.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPhLmR7ahiWeoByD3x153MVRO-Edyz8pE',
    appId: '1:332419219143:ios:6d7e33aafdb766afcd48e2',
    messagingSenderId: '332419219143',
    projectId: 'chatapp-48416',
    storageBucket: 'chatapp-48416.firebasestorage.app',
    iosClientId: '332419219143-02ntndntgoqsotdhc4c1re9oiabisuqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPhLmR7ahiWeoByD3x153MVRO-Edyz8pE',
    appId: '1:332419219143:ios:6d7e33aafdb766afcd48e2',
    messagingSenderId: '332419219143',
    projectId: 'chatapp-48416',
    storageBucket: 'chatapp-48416.firebasestorage.app',
    iosClientId: '332419219143-02ntndntgoqsotdhc4c1re9oiabisuqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNHHOBYhC1ZYc1KDuQel24iCgk-5lsrCI',
    appId: '1:332419219143:web:b68e5b3925c8c8b4cd48e2',
    messagingSenderId: '332419219143',
    projectId: 'chatapp-48416',
    authDomain: 'chatapp-48416.firebaseapp.com',
    storageBucket: 'chatapp-48416.firebasestorage.app',
    measurementId: 'G-JM1ZTFGSLV',
  );
}
